### ISSUE TITLE
Error that we should handle more gracefully

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/rudaux#149]
The current vsn of rudaux (`prefect_by_assignment` branch, which will soon be on `master`) had the following error happen:

```
[2021-10-07 23:21:06+0000] INFO - prefect.TaskRunner | FAIL signal raised: FAIL('Docker error autograding submission dsci100-001-num: tutorial_04-num : 
Student: exited with status exited,  
[AutogradeApp | INFO] Creating/updating student with ID \'stuentx\': {}\n
[AutogradeApp | INFO] Overwriting files with master versions from the source directory\n
[AutogradeApp | INFO] Copying /home/jupyter/source/./tutorial_04/mcdonalds.jpg -> /home/jupyter/autograded/studentx/tutorial_04/mcdonalds.jpg\n
[AutogradeAp | INFO] Copying /home/jupyter/source/./tutorial_04/tests_tutorial_04.R -> /home/jupyter/autograded/studentx/tutorial_04/tests_tutorial_04.R\n
[AutogradeApp | INFO] Copying /home/jupyter/source/./tutorial_04/data/fast_food.csv -> /home/jupyter/autograded/studentx/tutorial_04/data/fast_food.csv\n
[AutogradeApp | INFO] Copying /home/jupyter/source/./tutorial_04/data/insurance.csv -> /home/jupyter/autograded/studentx/tutorial_04/data/insurance.csv\n
[AutogradeApp | INFO] Copying /home/jupyter/source/./tutorial_04/clea$up_tutorial_04.R -> /home/jupyter/autograded/studentx/tutorial_04/cleanup_tutorial_04.R\n
[AutogradeApp | INFO] Sanitizing /home/jupyter/submitted/studentx/tutorial_04/tutorial_04.ipynb\n
[AutogradeApp | INFO] Converting notebook /home/jupyter/submitted/stu$entx/tutorial_04/tutorial_04.ipynb\n
[AutogradeApp | WARNING] Attribute \'checksum\' for cell cell-a5dc720f9e5813bd has changed! (should be: ad910ac09ba62c22f1e065b68b22ee7c, got: 0616a476231c2f9c184924467c066b11)\n
[AutogradeApp | INFO] Writing 43686 bytes to /h$me/jupyter/autograded/studentx/tutorial_04/tutorial_04.ipynb\n
[AutogradeApp | INFO] Autograding /home/jupyter/autograded/studentx/tutorial_04/tutorial_04.ipynb\n
[AutogradeApp | INFO] Converting notebook /home/jupyter/autograded/studentx/tutorial_04/tutorial_04.ipynb\nR_zmq_bind errno: 98 strerror: Address already in use\n
[AutogradeApp | INFO] Executing notebook with kernel: ir\nWarning message:\nIn zmq.bind(sockets$iopub, url_with_port("iopub_port")) :\n  zmq.bind fails, tcp://127.0.0.1:54176\n
[AutogradeApp | ERROR] There was an error processing assignment: /home/jupyter/submitted/studentx/tutorial_04\n
[AutogradeApp | ERROR] Traceback (most recent call last):\n      File "/opt/conda/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 589, in run_cell\n
        msg = self.kc.iopub_channel.get_msg(timeout=timeout)\n      File "/opt/conda/lib/python3.8/site-packages/jupyter_client/blocking/channels.py", line 54, in get_msg\n        raise Empty\n    _queue.Empty\n    \n    During handling of the above exception, another
 exception occurred:\n    \n    Traceback (most recent call last):\n      File "/opt/conda/lib/python3.8/site-packages/nbgrader/converters/base.py", line 336, in convert_notebooks\n        self.convert_single_notebook(notebook_filename)\n      File "/opt/conda/lib/pyt
hon3.8/site-packages/nbgrader/converters/autograde.py", line 195, in convert_single_notebook\n        super(Autograde, self).convert_single_notebook(notebook_filename)\n      File "/opt/conda/lib/python3.8/site-packages/nbgrader/converters/base.py", line 292, in conve
rt_single_notebook\n        output, resources = self.exporter.from_filename(notebook_filename, resources=resources)\n      File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename\n        return self.from_file(f, resou
rces=resources, **kw)\n      File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file\n        return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)\n      File "/opt/conda/lib/
python3.8/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node\n        nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)\n      File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporte
r.py", line 139, in from_notebook_node\n        nb_copy, resources = self._preprocess(nb_copy, resources)\n      File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess\n        nbc, resc = preprocessor(nbc, resc)\n     
 File "/opt/conda/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__\n        return self.preprocess(nb, resources)\n      File "/opt/conda/lib/python3.8/site-packages/nbgrader/preprocessors/execute.py", line 41, in preprocess\n        
output = super(Execute, self).preprocess(nb, resources)\n      File "/opt/conda/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess\n        nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)\n      File "/o
pt/conda/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess\n        nb.cells[index], resources = self.preprocess_cell(cell, resources, index)\n      File "/opt/conda/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", li
ne 438, in preprocess_cell\n        reply, outputs = self.run_cell(cell, cell_index, store_history)\n      File "/opt/conda/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 597, in run_cell\n        raise TimeoutError("Timeout waiting for IOPub ou
tput")\n    TimeoutError: Timeout waiting for IOPub output\n    \n
[AutogradeApp | WARNING] Removing failed assignment: /home/jupyter/autograded/studentx/tutorial_04\n
[AutogradeApp | ERROR] There was an error processing assignment \'tutorial_04\' for student \'st
udentx\'\n
[AutogradeApp | ERROR] Please see the the above traceback for details on the specific errors on the above failures.\n',)
[2021-10-07 23:21:06+0000] INFO - prefect.TaskRunner | Task 'autograde[15]': Finished task run for task with final state: 'Failed'
```

Rudaux currently just halts processing that assignment. Probably should do something a bit more graceful there. I think in the case of this particular error, a retry or two is warranted (when I reran the flow afterwards, they were graded properly).

**Comment by trevorcampbell** [comment]
[2021-12-02 06:32:51+0000] INFO - dsci100-004-snap - prefect.get_assignments | GET request to URL: https://canvas.ubc.ca/api/v1/courses/xxxx/assignments/yyyy/overrides
[2021-12-02 06:32:51+0000] INFO - dsci100-001-snap - prefect.get_assignments | GET request to URL: https://canvas.ubc.ca/api/v1/courses/xxxx/assignments/yyyy/overrides
[2021-12-02 06:32:51+0000] INFO - dsci100-004-snap - prefect.get_assignments | Retrieved 21 assignments from LMS for dsci100-004
[2021-12-02 06:32:52+0000] INFO - dsci100-004-snap - prefect.TaskRunner | Task 'get_assignments': Finished task run for task with final state: 'Success'
[2021-12-02 06:32:52+0000] INFO - dsci100-004-snap - prefect.TaskRunner | Task 'get_all_snapshots': Starting task run...
[2021-12-02 06:32:52+0000] INFO - dsci100-004-snap - prefect.TaskRunner | Task 'get_all_snapshots': Finished task run for task with final state: 'Success'
[2021-12-02 06:32:52+0000] INFO - dsci100-004-snap - prefect.TaskRunner | Task 'get_existing_snapshots': Starting task run...
[2021-12-02 06:32:52+0000] INFO - dsci100-004-snap - prefect.get_existing_snapshots | Opening ssh connection to student-url.com
[2021-12-02 06:32:52+0000] ERROR - dsci100-004-snap - prefect.TaskRunner | Task 'get_existing_snapshots': Exception encountered during task execution!
Traceback (most recent call last):
  File "/home/stty2u/.local/lib/python3.6/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/stty2u/.local/lib/python3.6/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/home/stty2u/.local/lib/python3.6/site-packages/paramiko/packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rudaux/snapshot.py", line 110, in _ssh_list_snapshot_names
    client = _ssh_open(config, course_id)
  File "/usr/local/lib/python3.6/site-packages/rudaux/snapshot.py", line 41, in _ssh_open
    client.connect(stu_ssh['hostname'], stu_ssh['port'], stu_ssh['user'], allow_agent=True)
  File "/home/stty2u/.local/lib/python3.6/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/home/stty2u/.local/lib/python3.6/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/home/stty2u/.local/lib/python3.6/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/home/stty2u/.local/lib/python3.6/site-packages/paramiko/transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/prefect/engine/task_runner.py", line 863, in get_task_run_state
    logger=self.logger,
  File "/usr/local/lib/python3.6/site-packages/prefect/utilities/executors.py", line 445, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.6/site-packages/rudaux/snapshot.py", line 153, in get_existing_snapshots
    existing_snaps = _ssh_list_snapshot_names(config, course_id)
  File "/usr/local/lib/python3.6/site-packages/rudaux/snapshot.py", line 116, in _ssh_list_snapshot_names
    client.close()
UnboundLocalError: local variable 'client' referenced before assignment
[2021-12-02 06:32:52+0000] INFO - dsci100-004-snap - prefect.TaskRunner | Task 'get_existing_snapshots': Finished task run for task with final state: 'Failed'

**Comment by trevorcampbell** [comment]
Dec 21 of the Fall 2021 semester, after final exam -- For some reason some of my students are appearing with registration dates of Dec 20. Rudaux then tries to give them an extension to Dec 27. 

We should include a config parameter that specifies the final course add date so that even if a student's reg date is erroneously updated late in the course, rudaux won't give them a weird extension.

For example, in the autoext module:
```
[2021-12-21 16:01:41+0000] INFO - dsci100-001-autoext - prefect.get_latereg_overrides[0] | Student Firstname Lastname needs an extension on assignment worksheet_01
[2021-12-21 16:01:41+0000] INFO - dsci100-001-autoext - prefect.get_latereg_overrides[0] | Student registration date: 2021-12-20T23:18:07+00:00    Status: active
[2021-12-21 16:01:41+0000] INFO - dsci100-001-autoext - prefect.get_latereg_overrides[0] | Assignment unlock: 2021-09-09T22:30:00+00:00    Assignment deadline: 2021-09-12T06:59:59+00:00
[2021-12-21 16:01:41+0000] INFO - dsci100-001-autoext - prefect.get_latereg_overrides[0] | Current student-specific due date: Sat 2021-09-11 23:59:59 from override: False
[2021-12-21 16:01:41+0000] INFO - dsci100-001-autoext - prefect.get_latereg_overrides[0] | Late registration extension date: Mon 2021-12-27 23:59:59
[2021-12-21 16:01:41+0000] INFO - dsci100-001-autoext - prefect.get_latereg_overrides[0] | Creating automatic late registration extension.
```

I haven't fixed the autoext module, but I have halted it (since I don't need it any more anyway for this semester).
